### PR TITLE
touched up the sell.html page styling only

### PR DESCRIPTION
**Pull request by raujimenez**
image

Only styling done on this pr, Currently working on changing the textarea where users are to put their description.

### CODE REVIEW

**Comment by raujimenez** [comment]
made the editor look better 
image

**Comment by raujimenez** [comment]
example of individual listing page
image

**Comment by raujimenez** [comment]
image
Buy button!

**Review by lsj1124 — APPROVED** [review]
It looks awesome! Thanks for your contribution!

**Pull request merged**
